version: '2'

services:
    web:
        image: lavoweb/php-7.4
        ports:
            - "3000:80"
        volumes:
            - ./www:/var/www/html                    
        links:
            - db:db
    db:
        image: mysql
        volumes:
            - /docker/mysql:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=licinfo2020
    myadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - "8080:80"
        links:
            - db:db

